name: Publish on PyPi and Build binary

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            python3 -m pip install -U pip setuptools wheel twine
            pip3 install .
      - name: Building
        run: make build
      - name: Publishing
        run: "python3 -m twine upload dist/* -u __token__ -p '${{ secrets.PYPI_TOKEN }}'"

  build_bin:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools wheel twine
          pip3 install .

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: './'
  
      - uses: actions/upload-artifact@v2
        with:
          name: 'rofi-notion'
          path: ./dist/linux
