name: Publish on PyPi

on:
  release:
    types: [ created, edited ]
  workflow_dispatch:

jobs:
  publish:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            python3 -m pip install -U pip setuptools wheel twine
            pip3 install .
      - name: Building
        run: make build
      - name: Publishing
        run: "python3 -m twine upload dist/* -u __token__ -p '${{ secrets.PYPI_TOKEN }}'"
  